### PR TITLE
Upgrade react-related dependencies

### PR DESCRIPTION
**Pull request by JackHowa**
- Noticed the pre-hooks react dev dependency 
- Reason to do this was I've noticed mismatched react versions errors in my tests as warnings 
- Tests are passing as expected
- Hope this isn't a bother, feel free to deny or suggest changes

### CODE REVIEW

**Comment by treyhuffine** [comment]
Thanks @JackHowa! Were there any changes to the package.json file as well or was it all just in the lockfile?

**Comment by JackHowa** [comment]
All the lockfile. Looks like we're still good from the `package.json` versioning preventing major version upgrades https://github.com/treyhuffine/is-react/blob/master/package.json#L14

If you want, I can be more explicit in the `package.json`, specifying a version.

**Comment by JackHowa** [comment]
Updated to be more explicit

**Comment by treyhuffine** [comment]
Thanks I'll publish to npm now

**Comment by JackHowa** [comment]
Thanks for such quick responses @treyhuffine -- hope you're doing well

**Comment by treyhuffine** [comment]
Of course! Thanks for the PR

**Pull request merged**
